version: '3'
services:
  frontend:
    build: frontend/
    container_name: tstats-frontend
    ports:
      - "8000:3000"
    depends_on:
      - postgres
  backend:
    build: backend/
    container_name: tstats-backend
    ports:
      - "8001:3000"
    env_file: backend/.env
    environment:
      - RUST_BACKTRACE=1
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: tstats-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
