[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] } # Apache
rosu-v2 = "0.4.0" # MIT
serde = "1.0.139" # Apache/MIT
serde_json = "1.0.82" # Apache/MIT
sqlx = { version = "0.6.1", features = ["runtime-tokio-rustls", "macros", "sqlite", "postgres"]} # Apache/MIT
dotenv = "0.15.0" # MIT
redis = { version = "0.21.6", features = ["tokio-comp"] } # BSD3


[toolchain]
channel = "nightly"