[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
dotenvy = "0.15"
rosu-v2 = "0.8"
serde = "1.0"
serde_json = "1.0"
surrealdb = "1.0.0-beta.9"
tokio = { version = "1.29", features = ["rt-multi-thread", "macros"] }
