//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "pool_bracket"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub tournament_id: i32,
    pub stage_order: i16,
    pub bracket_order: i16,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TournamentId,
    StageOrder,
    BracketOrder,
    Name,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TournamentId,
    StageOrder,
    BracketOrder,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i32, i16, i16);
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    PoolMap,
    Stage,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TournamentId => ColumnType::Integer.def(),
            Self::StageOrder => ColumnType::SmallInteger.def(),
            Self::BracketOrder => ColumnType::SmallInteger.def(),
            Self::Name => ColumnType::String(Some(10u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::PoolMap => Entity::has_many(super::pool_map::Entity).into(),
            Self::Stage => Entity::belongs_to(super::stage::Entity)
                .from((Column::TournamentId, Column::StageOrder))
                .to((
                    super::stage::Column::TournamentId,
                    super::stage::Column::StageOrder,
                ))
                .into(),
        }
    }
}

impl Related<super::pool_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PoolMap.def()
    }
}

impl Related<super::stage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stage.def()
    }
}

impl Related<super::tournament::Entity> for Entity {
    fn to() -> RelationDef {
        super::stage::Relation::Tournament.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stage::Relation::PoolBracket.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
