/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/owc23": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** hi */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Tournament"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Tournament"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Request Auth Code */
        get: {
            parameters: {
                query: {
                    returnUrl: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RequestAuthCodeResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Deliver Auth Code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeliverAuthCodeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DeliverAuthCodeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Authenticated User */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AuthenticatedUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/:tournament_id/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch all stages for a tournament. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Stage"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/:tournament_id/stage/{stage_order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single stage for a tournament. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournament_id: number;
                    stage_order: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Stage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedUser: {
            /** Format: uint32 */
            userId: number;
            username: string;
            country: string;
        };
        Country: {
            countryCode: string;
        };
        DeliverAuthCodeRequest: {
            authCode: string;
            state: string;
        };
        DeliverAuthCodeResponse: {
            returnUrl: string;
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @enum {string} */
        OsuMode: "Catch" | "Mania" | "Osu" | "Taiko";
        RankRange: {
            /** Format: uint64 */
            min: number;
            /** Format: uint64 */
            max: number;
        };
        RequestAuthCodeResponse: {
            authUrl: string;
        };
        Stage: {
            /** Format: uint64 */
            tournamentId: number;
            /** Format: uint64 */
            stageOrder: number;
            name: string;
            /** Format: uint64 */
            bestOf: number;
            /** Format: naive-date */
            startDate?: string;
            /** Format: naive-date */
            endDate?: string;
        };
        Tournament: {
            /** Format: uint64 */
            id: number;
            name: string;
            shorthand: string;
            /** Format: uint64 */
            format: number;
            bws: boolean;
            mode: components["schemas"]["OsuMode"];
            /** Format: naive-date */
            startDate?: string;
            /** Format: naive-date */
            endDate?: string;
            banner?: number[];
            rankRestrictions: components["schemas"]["RankRange"][];
            countryRestrictions: components["schemas"]["Country"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AuthenticatedUser = components['schemas']['AuthenticatedUser'];
export type Country = components['schemas']['Country'];
export type DeliverAuthCodeRequest = components['schemas']['DeliverAuthCodeRequest'];
export type DeliverAuthCodeResponse = components['schemas']['DeliverAuthCodeResponse'];
export type OsuMode = components['schemas']['OsuMode'];
export type RankRange = components['schemas']['RankRange'];
export type RequestAuthCodeResponse = components['schemas']['RequestAuthCodeResponse'];
export type Stage = components['schemas']['Stage'];
export type Tournament = components['schemas']['Tournament'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
