[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

model = { path = "../model" }
utils = { path = "../utils" }

chrono.workspace = true
config.workspace = true
deadpool-redis.workspace = true
# Read .env files
dotenvy = "0.15"
futures.workspace = true
# HTTP utilities
http = "1.1"
# Iterator utilities
itertools = "0.14"
jwt.workspace = true
# Convenient error handling
miette.workspace = true
# Authentication using OAuth2
oauth2 = "5"
poem.workspace = true
poem-openapi.workspace = true
rand = "0.8"
# Redis client
redis.workspace = true
# Osu API connector
rosu-v2.workspace = true
sea-orm.workspace = true
# Serialization/Deserialization
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
# Creating error types conveniently
thiserror = "2.0"
# Async runtime
tokio.workspace = true
# Instrumentation and logging
tracing = "0.1"
# URL-related utilities
url.workspace = true
urlencoding = "2.1"
rand_chacha = "0.9"
reqwest = "0.12"
scrypt = "0.11.0"
base64 = "0.22.0"
aes-gcm = { version = "0.10.3", features = ["std"] }
tracing-error = "0.2.0"
tracing-subscriber.workspace = true

[dev-dependencies]
ctor = "0.2.7"
