[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

model = { path = "../model" }
proto = { path = "../proto" }

# Backend Framework
axum = { version = "0.6" }
axum-macros = "0.3"

# Read .env files
dotenvy = "0.15"
futures = "0.3.28"
miette = { version = "5.10.0", features = ["fancy"] }
prost = { version = "0.12" }
rand = "0.8"
redis = { version = "0.23.3", features = ["tokio-comp", "serde_json", "json"] }
rosu-v2 = { version = "0.8", features = ["serialize"] }
sea-orm = { version = "0.12.4", features = ["runtime-tokio-rustls"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.33", features = ["rt-multi-thread", "macros", "signal"] }
tonic = { version = "0.10", features = ["transport"] }
tonic-reflection = "0.10"
tower-http = { version = "0.4", features = ["cors", "trace"] }
tracing = "0.1"
tracing-log = { version = "0.2" }
url = "2.4.1"
utoipa = { version = "3.4.3", features = ["axum_extras", "yaml"] }
utoipa-swagger-ui = { version = "3.1.4", features = ["axum"] }
log = "0.4.20"
