//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "score"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub team_id: i32,
    pub player_id: i32,
    pub tournament_id: i32,
    pub stage_order: i16,
    pub bracket_order: i16,
    pub map_order: i16,
    pub match_id: i32,
    pub score: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TeamId,
    PlayerId,
    TournamentId,
    StageOrder,
    BracketOrder,
    MapOrder,
    MatchId,
    Score,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PlayerId,
    TournamentId,
    StageOrder,
    BracketOrder,
    MapOrder,
    MatchId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i32, i32, i16, i16, i16, i32);
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Match,
    PoolMap,
    TeamMember,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TeamId => ColumnType::Integer.def(),
            Self::PlayerId => ColumnType::Integer.def(),
            Self::TournamentId => ColumnType::Integer.def(),
            Self::StageOrder => ColumnType::SmallInteger.def(),
            Self::BracketOrder => ColumnType::SmallInteger.def(),
            Self::MapOrder => ColumnType::SmallInteger.def(),
            Self::MatchId => ColumnType::Integer.def(),
            Self::Score => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Match => Entity::belongs_to(super::r#match::Entity)
                .from(Column::MatchId)
                .to(super::r#match::Column::Id)
                .into(),
            Self::PoolMap => Entity::belongs_to(super::pool_map::Entity)
                .from((
                    Column::TournamentId,
                    Column::StageOrder,
                    Column::BracketOrder,
                    Column::MapOrder,
                ))
                .to((
                    super::pool_map::Column::TournamentId,
                    super::pool_map::Column::StageOrder,
                    super::pool_map::Column::BracketOrder,
                    super::pool_map::Column::MapOrder,
                ))
                .into(),
            Self::TeamMember => Entity::belongs_to(super::team_member::Entity)
                .from((Column::TeamId, Column::PlayerId))
                .to((
                    super::team_member::Column::TeamId,
                    super::team_member::Column::UserId,
                ))
                .into(),
        }
    }
}

impl Related<super::r#match::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Match.def()
    }
}

impl Related<super::pool_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PoolMap.def()
    }
}

impl Related<super::team_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamMember.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        super::team_member::Relation::Team.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::team_member::Relation::Score.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
